"use client";

import * as Dialog from "@radix-ui/react-dialog";
import Link from "next/link";
import { usePathname } from "next/navigation";
import {
  BarChart3,
  BookOpenText,
  ChevronRight,
  FileText,
  Gauge,
  Play,
  Presentation,
  SlidersHorizontal,
  X,
} from "lucide-react";
import { useState } from "react";

const steps = [
  {
    title: "Market changed",
    detail:
      "Open the executive command centre and locate the bullish market change.",
    href: "/dashboard?story=market-change",
    action: "Open command centre",
    icon: Gauge,
  },
  {
    title: "Explain why",
    detail:
      "Open the real Explain drawer with supporting, contradicting, model and freshness evidence.",
    href: "/dashboard?story=why",
    action: "Explain the outlook",
    icon: BarChart3,
  },
  {
    title: "Inspect sources",
    detail:
      "Expand the source records and open the cited EIA or DORA evidence.",
    href: "/dashboard?story=why",
    action: "Review evidence",
    icon: BookOpenText,
  },
  {
    title: "Stress 30-day disruption",
    detail:
      "Run the actual scenario engine with a material route disruption lasting 30 days.",
    href: "/scenarios?story=disruption-30d",
    action: "Run scenario",
    icon: SlidersHorizontal,
  },
  {
    title: "Preview Monday brief",
    detail:
      "Open the stored responsive HTML briefing generated by DORA's reporting service.",
    href: "/reports?story=preview",
    action: "Preview report",
    icon: FileText,
  },
] as const;

export function DemoStory() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);

  if (pathname === "/login") return null;

  return (
    <Dialog.Root open={open} onOpenChange={setOpen}>
      <Dialog.Trigger asChild>
        <button
          className="fixed bottom-5 left-5 z-40 flex h-11 items-center gap-2 rounded-full border border-white/70 bg-white/85 px-4 text-xs font-bold text-[var(--navy)] shadow-[var(--shadow-float)] backdrop-blur-xl"
          type="button"
        >
          <Presentation size={16} /> Demo Story
        </button>
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-50 bg-[rgba(13,38,56,.24)] backdrop-blur-[2px]" />
        <Dialog.Content className="fixed bottom-4 left-4 right-4 z-50 max-h-[calc(100vh-2rem)] overflow-y-auto rounded-[8px] border border-white/70 bg-[rgba(252,253,250,.97)] p-5 shadow-[var(--shadow-float)] outline-none sm:left-6 sm:right-auto sm:w-[440px] sm:p-6">
          <div className="flex items-start justify-between gap-3">
            <div>
              <div className="flex items-center gap-2 text-[10px] font-bold uppercase text-[var(--teal)]">
                <Play size={13} /> Five-minute narrative
              </div>
              <Dialog.Title className="mt-2 font-serif text-2xl text-[var(--navy)]">
                DORA Demo Story
              </Dialog.Title>
              <Dialog.Description className="mt-1 text-xs leading-5 text-[var(--ink-muted)]">
                Each step opens a real application capability and live API.
              </Dialog.Description>
            </div>
            <Dialog.Close
              className="dora-floating-control grid size-9 place-items-center"
              aria-label="Close Demo Story"
            >
              <X size={16} />
            </Dialog.Close>
          </div>
          <div className="mt-5 space-y-2">
            {steps.map((step, index) => {
              const Icon = step.icon;
              const active = index === currentStep;
              return (
                <div
                  className={`rounded-[8px] border p-4 ${active ? "border-[var(--teal-line)] bg-[var(--teal-soft)]" : "border-[var(--line)] bg-white/65"}`}
                  key={step.title}
                >
                  <div className="flex items-start gap-3">
                    <span
                      className={`grid size-8 shrink-0 place-items-center rounded-full text-[10px] font-bold ${active ? "bg-[var(--teal)] text-white" : "bg-[var(--surface-subtle)] text-[var(--ink-muted)]"}`}
                    >
                      {index + 1}
                    </span>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <Icon size={14} className="text-[var(--teal)]" />
                        <h3 className="text-xs font-bold text-[var(--navy)]">
                          {step.title}
                        </h3>
                      </div>
                      <p className="mt-1 text-[10px] leading-4 text-[var(--ink-muted)]">
                        {step.detail}
                      </p>
                      <Link
                        className="mt-3 inline-flex items-center gap-1 text-[10px] font-bold text-[var(--blue)]"
                        href={step.href}
                        onClick={() =>
                          setCurrentStep(Math.min(index + 1, steps.length - 1))
                        }
                      >
                        {step.action} <ChevronRight size={11} />
                      </Link>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
          <div className="mt-4 flex items-center justify-between text-[9px] text-[var(--ink-faint)]">
            <span>
              Step {currentStep + 1} of {steps.length}
            </span>
            <button
              type="button"
              onClick={() => setCurrentStep(0)}
              className="font-bold text-[var(--blue)]"
            >
              Restart story
            </button>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
